### PR TITLE
Message editing, use Telecom for calls, video messages

### PR DESCRIPTION
**Pull request by or-else**
Please test for bugs. Thanks!

### CODE REVIEW

**Comment by aforge** [comment]
Message editing & "Reply to" features aren't working: selecting a message and clicking on the corresponding buttons does nothing.
"Edit" button should be presented only for user's own messages (and not for other users' messages).
[device-2023-01-03-203808.webm](https://user-images.githubusercontent.com/45520561/210485912-b214c65c-2073-4486-b048-e0ac177066cf.webm)

**Comment by or-else** [comment]
> Message editing & "Reply to" features aren't working: selecting a message and clicking on the corresponding buttons does nothing.

Fixed. The actual fix is replacing `new PromisedReply<>(null)` with `new PromisedReply<>((Void[]) null)`.

> "Edit" button should be presented only for user's own messages (and not for other users' messages).

Fixed.

**Comment by aforge** [comment]
Here are some issues:
* Post a reply to an edited message. Then click on the quote. It should highlight the quoted message but doesn't.
* Post a video file as an attachment. The displayed size is zero:
andr-0

* Hitting the save button on the file attachment containing a video file plays it instead of saving.
* Posting video messages fails with `W/SqlStore: Failed to insert message: topic is null`
* App won't play inline video messages

**Comment by aforge** [comment]
> * Hitting the save button on the file attachment containing a video file plays it instead of saving.

Scratch that. It does save the file. The video player that showed up confused me.

**Comment by or-else** [comment]
> Post a reply to an edited message. Then click on the quote. It should highlight the quoted message but doesn't.

I cannot reproduce. There must be something more to it.

> Post a video file as an attachment. The displayed size is zero:

I could not reproduce but had some issues which could have been related. Please let me know if it's still happenning.

> Posting video messages fails with W/SqlStore: Failed to insert message: topic is null

Fixed

> App won't play inline video messages

Fixed

**Comment by aforge** [comment]
> > Post a reply to an edited message. Then click on the quote. It should highlight the quoted message but doesn't.
> 
> I cannot reproduce. There must be something more to it.

It appears to be working if you post a reply an edited message from Tindroid.
Here are steps to reproduce:
0. Log in as `alice` (Web), as `bob` (Tindroid).
1. Edit a message as `bob` in Tindroid.
2. Reply to the edited message as `alice` in Web
3. Tap on the quote in Tindroid. Nothing happens while it should highlight the edited message.

Btw, it appears to be a problem in the Web as well (just reverse the `alice` and `bob`)

> 
> > Post a video file as an attachment. The displayed size is zero:
> 
> I could not reproduce but had some issues which could have been related. Please let me know if it's still happenning.

Still getting it. I posted  https://user-images.githubusercontent.com/45520561/210872931-f29886ab-ef97-440c-8963-7714bce7126b.mp4 as a file attachment from Web (as `alice`) and opened Tindroid (as `bob`).

> 
> > Posting video messages fails with W/SqlStore: Failed to insert message: topic is null
> 
> Fixed
> 
> > App won't play inline video messages
> 
> Fixed

Interestingly enough, when I tried posting `small-vid.mp4` as a video message from Tindroid (I increased `max_message_size` in the server config to make sure the file would be posted inline), I got

```
E/AndroidRuntime: FATAL EXCEPTION: videoFrameCapture
    Process: co.tinode.tindroidx, PID: 20755
    java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
        at androidx.work.Data.toByteArrayInternal(Data.java:407)
        at androidx.work.Data$Builder.build(Data.java:957)
        at co.tinode.tindroid.AttachmentHandler.enqueueMsgAttachmentUploadRequest(AttachmentHandler.java:248)
        at co.tinode.tindroid.VideoViewFragment.lambda$sendVideo$5$co-tinode-tindroid-VideoViewFragment(VideoViewFragment.java:334)
        at co.tinode.tindroid.VideoViewFragment$$ExternalSyntheticLambda6.done(Unknown Source:6)
        at co.tinode.tindroid.VideoViewFragment.lambda$videoFrameCapture$6(VideoViewFragment.java:351)
        at co.tinode.tindroid.VideoViewFragment$$ExternalSyntheticLambda0.onPixelCopyFinished(Unknown Source:6)
        at android.view.PixelCopy$1.run(PixelCopy.java:191)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

It seems like it's some kind of a built-in limitation in Android...

**Comment by or-else** [comment]
> It seems like it's some kind of a built-in limitation in Android...

I've seen this before. It's not too hard to fix. I'll look into it.

**Comment by or-else** [comment]
> Still getting it. I posted

Is it posted inline?

**Comment by aforge** [comment]
Posting a large file (out of band) as a video message is failing with
```
E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/AttachmentHandler: File size is zero; uri=content://com.android.providers.downloads.documents/document/59; file=/document/59
```

**Comment by or-else** [comment]
> Posting a large file (out of band) as a video message is failing with

What's your Android API version?

**Comment by or-else** [comment]
> Still getting it. I posted https://user-images.githubusercontent.com/45520561/210872931-f29886ab-ef97-440c-8963-7714bce7126b.mp4 as a file attachment from Web (as alice) and opened Tindroid (as bob).

Fixed it in webapp. I also added handling of missing file size in entity data in Tindroid.

**Comment by aforge** [comment]
> > Posting a large file (out of band) as a video message is failing with
> 
> What's your Android API version?

Good point. Upgraded to 32. The error went away.

**Comment by or-else** [comment]
> Good point. Upgraded to 32. The error went away.

It still needs to be fixed on older Androids. What was your API version when it was failing?

**Comment by or-else** [comment]
All fixed except:

> Posting a large file (out of band) as a video message is failing with
> W/AttachmentHandler: File size is zero; uri=content://com.android.providers.downloads.documents/document/59; file=/document/59

I still cannot reproduce. I suspect it's dependent on the location of the file. Which folder is it in? 

> Post a reply to an edited message. Then click on the quote. It should highlight the quoted message but doesn't.

This is a bug in webapp. 

Unfortunately, there is a problem with VideoView on older Androids (~26 and below). It's buggy to the point of being unusable. It fails randomly while trying to play remote URLs because it sometimes decides that a URI starting with `http://` is a local `content://` URI. The only recommended fix is to replace VideoView with ExoPlayer. I guess I have to do it.

**Comment by aforge** [comment]
> 



> All fixed except:
> 
> > Posting a large file (out of band) as a video message is failing with
> > W/AttachmentHandler: File size is zero; uri=content://com.android.providers.downloads.documents/document/59; file=/document/59
> 
> I still cannot reproduce. I suspect it's dependent on the location of the file. Which folder is it in?

Files/Downloads folder. I can no longer reproduce it either (tested on a brand new Pixel 3/API 27 emulator).
Let's proceed as is.

> 
> > Post a reply to an edited message. Then click on the quote. It should highlight the quoted message but doesn't.
> 
> This is a bug in webapp.
> 
> Unfortunately, there is a problem with VideoView on older Androids (~26 and below). It's buggy to the point of being unusable. It fails randomly while trying to play remote URLs because it sometimes decides that a URI starting with `http://` is a local `content://` URI. The only recommended fix is to replace VideoView with ExoPlayer. I guess I have to do it.

**Review by aforge — APPROVED** [review]

**Pull request merged**
